spring:
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017/paymentsdb?authSource=admin
      auto-index-creation: true

server:
  port: 8080

logging:
  level:
    com.innowise: DEBUG
    org.springframework.data.mongodb: DEBUG